Add Capture::dead_with_options constructor
rust-pcap/pcap pull request #245
Opened 2022-07-16 18:11 UTC by gmacon

I realized that using a builder isn't actually a backwards-breaking change if I keep the existing method as a shortcut, so here it is.

Fixes #243

2022-07-19 11:19 UTC, Stargateur requested changes
I see better why you wanted this I'm never used this api so I'm limited to my review, does the default really make sense ? can we set a default linktype ?

2022-07-19 23:22 UTC, gmacon commented
We can set a default value for the linktype, but I didn't see an obvious default value. (I looked for a `DLT_UNSPECIFIED` or similar, but didn't find one.) What linktype do you want to be the default?

2022-07-19 23:24 UTC, gmacon commented on src/lib.rs
> +    pub fn activate(&self) -> Result<Capture<Dead>, Error> {
Sure, done.

2022-07-20 01:31 UTC, Stargateur commented
It was an open question, if there is none so be it.

2022-08-14 12:22 UTC, Wojtek242 commented
I find the motivation behind this PR good and would like to see it make into the code base, but I find the implementation highly inconsistent with the rest of the existing API.

In particular:
- None of the other capture types implement builders in the same way, you are. They effectively implement builders via `Capture<Inactive>`. Unfortunately, I don't think that's usable for `Capture<Dead>` due to it requiring a device
- `dead` and `dead_with_options` produce two different types which I find unexpected due to the inconsistency

I was contemplating having another Capture type to account for this, but that would also be inconsistent with the other captures as they all assume a `NonNull` pcap pointer.

Whilst ugly, I would prefer for consistency's sake if rather than having a builder, you implement only a single new method on `Capture<Dead>` called `dead_with_precision`. The current requirements do not justify breaking consistency.

2022-08-14 12:23 UTC, Wojtek242 requested changes
See my comment above (https://github.com/rust-pcap/pcap/pull/245#issuecomment-1214360067). I'm only adding this comment so that GH registers it's reviewed.

2022-08-14 12:24 UTC, Wojtek242 commented
Oh and if you do implement the changes, please make sure to rebase first to pick up the clippy lint fixes so that we can run the CI on your PR.

2022-08-14 23:46 UTC, gmacon commented
OK, done.

2022-08-15 08:08 UTC, Wojtek242 requested changes
Thanks for the changes. Happy to merge once the CI passes. It seems you will need to gate the new method behine `#[cfg(libpcap_1_5_0)]` just like `from_file_with_precision` is gated.

2022-08-15 18:07 UTC, Wojtek242 commented
And apologies for the extra work, but you might need to rebase again to avoid merge conflicts on the CHANGELOG.

2022-08-16 07:09 UTC, Wojtek242 approved these changes

2022-08-16 07:09 UTC, Wojtek242 commented
Thanks!

2022-08-16 07:09 UTC, merged