Add `lending-iter` feature
rust-pcap/pcap pull request #294
Opened 2023-02-26 19:30 UTC by Stargateur

This show how GATs can be used for our problem that lifetime of paquet is link to capture lifetime. However, this is behind a `lending-iter` feature that I think should be considered not a part of our public api.

2023-02-26 21:21 UTC, stappersg commented
![image](https://user-images.githubusercontent.com/35434094/221437941-8f53c996-9d2d-42ac-ba0b-b3287a4051ce.png)
Now complete or still _work in progress_?

2023-05-10 20:05 UTC, Wojtek242 requested changes
I finally got around to having a look. Thanks for the PR! Looks good to me. Just fix a few things for consistency and I will merge.

2023-05-10 20:05 UTC, Wojtek242 commented on Cargo.toml
> +version = "0.1.1"
For consistency, please make this dependency one line, like the other dependencies above and put it under the line with the `futures` package.

2023-05-10 20:05 UTC, Wojtek242 commented on README.md
> +Use at your own risk, we do not considered this our public API yet.
Small typo: "considered" -> "consider"

2023-05-10 20:05 UTC, Wojtek242 commented on README.md
> +This use `gat-std` crate to have a common lending iterator, this crate is not a lot used so this may change later. See `lendingiterprint` example.
No need for so much detail. For consistency with the description of `capture-stream`, please change the description to something like:

Use the `lending-iter` feature to enable the lending packet iterator. See the `lendingiterprint` example.

2023-05-10 20:11 UTC, Wojtek242 commented
> I finally got around to having a look. Thanks for the PR! Looks good to me. Just fix a few things for consistency and I will merge.

Oh, and please add a note to the CHANGELOG. After I merge, I will release `1.1.0` with this feature.

2023-05-11 23:25 UTC, Stargateur commented
> Oh, and please add a note to the CHANGELOG. After I merge, I will release 1.1.0 with this feature.

I already did no ?

2023-05-12 06:18 UTC, Wojtek242 commented
> > Oh, and please add a note to the CHANGELOG. After I merge, I will release 1.1.0 with this feature.
> 
> I already did no ?

Ah, sorry. Yes, you did. It just occurred to me later and I didn't check.

2023-05-12 06:18 UTC, Wojtek242 commented
Looks good to me. Thanks! I will merge now.

2023-05-12 06:18 UTC, merged