Add example with saving packets to different files
rust-pcap/pcap pull request #302
Opened 2023-06-22 20:04 UTC by maybe-hello-world

This PR adds an example of using Capture::dead() to save packets from an active Capture to different files.

## Reason
Splitting the PCAP stream (either in-flight or from an existing file) is a common task, and currently, no example covers it. If a user tries to create `SaveFile` from the same active Capture, errors are not helping a lot (current errors are about mutable and immutable borrows, while the right approach - create new Captures with a `dead` parameter).

2023-06-22 21:36 UTC, Stargateur requested changes
don't like much this infinite loop

2023-06-22 21:36 UTC, Stargateur commented on examples/savemultiplefiles.rs
> +    let mut counter = 0;
I would prefer 0usize

2023-06-22 21:36 UTC, Stargateur commented on examples/savemultiplefiles.rs
> +
A call to flush would allow to check for write error

2023-06-23 02:34 UTC, maybe-hello-world commented
Switched from infinite loop to just 5 files. You're correct, for this example's purposes it's fine, and most likely we don't want some example running forever.

2023-06-23 13:18 UTC, Stargateur commented
Now you can use the for loop count instead of doing your counter manually :p

2023-06-25 03:49 UTC, maybe-hello-world commented
Thanks, updated. :)

2023-06-25 08:44 UTC, merged