Add a binding for pcap_loop
rust-pcap/pcap pull request #310
Opened 2023-10-05 00:50 UTC by saethlin

I recently ran into a situation where a tool I help maintain and `tcpdump` had different behavior with a somewhat exotic libpcap implementation. I eventually tracked this down to the fact that `tcpdump` uses `pcap_loop` and since said tool is going through this crate, it was using `pcap_next_ex`. This difference was actually a bug in the libpcap implementation, I spent a frustrating amount of time convincing people that the bug was in libpcap.

Since that time, I've been wanting a way to call `pcap_loop` from this crate, because that would have made my life a lot easier. So I finally got around to putting one together, here it is.

I don't really care about the public API. Ideas like a better name are very welcome.

2023-10-05 11:02 UTC, Stargateur requested changes
name it run (commun for loop in rust lib) instead of loop maybe, but I don't like the pcap in front for sure.

2024-02-25 20:20 UTC, Wojtek242 commented
Due to significant changes on `main` since this was proposed, I will close it. If you get around to addressing the comments and adapting to the current code base, I'll be happy to review it.

2024-02-25 20:20 UTC, closed without merging

2024-02-26 02:33 UTC, saethlin commented on src/lib.rs
> +                ptr::addr_of_mut!(handler).cast(),
I'm not sure what you mean to comment on here. Perhaps you mean `ptr::addr_of_mut!`? If the place it's passed has no projections, then there are no preconditions. And you can even `addr_of!(*ptr)` for any `ptr`: https://github.com/rust-lang/reference/pull/1387

2024-02-26 02:36 UTC, saethlin commented
_sigh_ I force-pushed to the branch before re-opening the PR which has killed the PR. I'll open a fresh one.